// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	   int limit=Integer.parseInt(args[0]);
	   int countBig=0;//will count the numbers above 0.5
	   int countSmall=0;//will count the numbers below 0.5
	   for(int i=0;i<limit;i++)
	   {
		double numberRandom=(Math.random());
		if (numberRandom>0.5)countBig++;
		else countSmall++;
	   }
	   System.out.println("> 0.5:  "+countBig+" times");
	   System.out.println("<= 0.5:  "+countSmall+" times");


	}
}
